const cartData = [
  {
    id: "01",
    name: "妙語說書人",
    price: 550,
    image: "./images/妙語說書人1.jpg",
    category: "funny",
  },
  {
    id: "02",
    name: "矮人礦坑",
    price: 700,
    image: "./images/矮人礦坑2.jpg",
    category: "funny",
  },
  {
    id: "03",
    name: "Bang",
    price: 490,
    image: "./images/bang3.jpeg",
    category: "others",
  },
  {
    id: "04",
    name: "目擊者之夜",
    price: 980,
    image: "./images/目擊者之夜4.jpeg",
    category: "party",
  },
  {
    id: "05",
    name: "卡坦島",
    price: 650,
    image: "./images/卡坦島5.jpeg",
    category: "funny",
  },
  {
    id: "06",
    name: "石器時代",
    price: 690,
    image: "./images/石器時代6.jpeg",
    category: "party",
  },
  {
    id: "07",
    name: "阿瓦隆",
    price: 990,
    image: "./images/阿瓦隆7.png",
    category: "funny",
  },
  {
    id: "08",
    name: "情書",
    price: 1080,
    image: "./images/情書8.jpeg",
    category: "hot",
  },
  {
    id: "09",
    name: "拉密",
    price: 780,
    image: "./images/拉密9.webp",
    category: "party",
  },
  {
    id: "10",
    name: "狼人殺",
    price: 880,
    image: "./images/狼人殺10.webp",
    category: "hot",
  },
  {
    id: "11",
    name: "卡卡頌",
    price: 590,
    image: "./images/卡卡頌11.jpeg",
    category: "others",
  },
  {
    id: "12",
    name: "德國心臟病",
    price: 490,
    image: "./images/德國心臟病12.webp",
    category: "party",
  },
  {
    id: "13",
    name: "德國蟑螂",
    price: 650,
    image: "./images/德國蟑螂13.jpeg",
    category: "others",
  },
  {
    id: "14",
    name: "誰是牛頭王",
    price: 480,
    image: "./images/誰是牛頭王14.jpeg",
    category: "party",
  },
  {
    id: "15",
    name: "乾杯",
    price: 660,
    image: "./images/乾杯15.jpeg",
    category: "hot",
  },
  {
    id: "16",
    name: "不在場證明",
    price: 780,
    image: "./images/不在場證明16.jpeg",
    category: "party",
  },
  {
    id: "17",
    name: "伊斯坦堡",
    price: 990,
    image: "./images/伊斯坦堡17.jpeg",
    category: "hot",
  },
  {
    id: "18",
    name: "作弊飛蛾",
    price: 590,
    image: "./images/作弊飛蛾18.jpeg",
    category: "hot",
  },
  {
    id: "19",
    name: "你刺我殺他",
    price: 550,
    image: "./images/你刺我殺他19.jpeg",
    category: "party",
  },
  {
    id: "20",
    name: "冰山疊企鵝",
    price: 680,
    image: "./images/冰山疊企鵝20.jpeg",
    category: "funny",
  },
  {
    id: "21",
    name: "估估劃劃",
    price: 650,
    image: "./images/估姑劃劃21.webp",
    category: "others",
  },
  {
    id: "22",
    name: "uno",
    price: 390,
    image: "./images/uno22.webp",
    category: "party",
  },
  {
    id: "23",
    name: "動手不動口",
    price: 790,
    image: "./images/動手不動口23.webp",
    category: "party",
  },
  {
    id: "24",
    name: "快手疊杯",
    price: 580,
    image: "./images/快手疊杯24.webp",
    category: "funny",
  },
  {
    id: "25",
    name: "奶酪大盜",
    price: 550,
    image: "./images/奶酪大盜25.webp",
    category: "hot",
  },
  {
    id: "26",
    name: "傳情畫意",
    price: 750,
    image: "./images/傳情畫意26.webp",
    category: "others",
  },
  {
    id: "27",
    name: "腦洞量表",
    price: 990,
    image: "./images/腦洞量表27.webp",
    category: "hot",
  },
  {
    id: "28",
    name: "馬可波羅",
    price: 680,
    image: "./images/馬可波羅28.webp",
    category: "funny",
  },
  {
    id: "29",
    name: "名畫神偷",
    price: 550,
    image: "./images/名畫神偷29.jpeg",
    category: "party",
  },
  {
    id: "30",
    name: "城市規劃師",
    price: 1190,
    image: "./images/城市規劃師30.jpeg",
    category: "others",
  },
  {
    id: "31",
    name: "萬獸酒吧",
    price: 770,
    image: "./images/萬獸酒吧31.jpeg",
    category: "others",
  },
  {
    id: "32",
    name: "不要命的冒險",
    price: 880,
    image: "./images/不要命的冒險32.jpeg",
    category: "hot",
  },
  {
    id: "33",
    name: "呼拉大師",
    price: 580,
    image: "./images/呼拉大師33.jpeg",
    category: "funny",
  },
  {
    id: "34",
    name: "惡魔島",
    price: 690,
    image: "./images/惡魔島34.jpeg",
    category: "others",
  },
  {
    id: "35",
    name: "滿腦子番茄",
    price: 550,
    image: "./images/滿腦子番茄35.webp",
    category: "party",
  },
  {
    id: "36",
    name: "瘋狂科學家",
    price: 790,
    image: "./images/瘋狂科學家36.webp",
    category: "funny",
  },
  {
    id: "37",
    name: "起司天堂",
    price: 1200,
    image: "./images/起司天堂37.webp",
    category: "hot",
  },
  {
    id: "38",
    name: "抓鬼大隊",
    price: 760,
    image: "./images/抓鬼大隊38.webp",
    category: "hot",
  },
  {
    id: "39",
    name: "動物疊疊樂",
    price: 890,
    image: "./images/動物疊疊樂39.webp",
    category: "party",
  },
  {
    id: "40",
    name: "種豆",
    price: 680,
    image: "./images/種豆40.webp",
    category: "funny",
  },
  {
    id: "41",
    name: "陛下",
    price: 870,
    image: "./images/陛下41.webp",
    category: "others",
  },
  {
    id: "42",
    name: "上流社會",
    price: 660,
    image: "./images/上流社會42.webp",
    category: "others",
  },
  {
    id: "43",
    name: "病毒在跳舞",
    price: 770,
    image: "./images/病毒在跳舞43.webp",
    category: "hot",
  },
  {
    id: "44",
    name: "瘟疫危機",
    price: 1080,
    image: "./images/瘟疫危機44.webp",
    category: "others",
  },
  {
    id: "45",
    name: "黃牌",
    price: 480,
    image: "./images/黃牌45.jpeg",
    category: "funny",
  },
  {
    id: "46",
    name: "動物園",
    price: 480,
    image: "./images/動物園46.jpeg",
    category: "funny",
  },
  {
    id: "47",
    name: "閃靈快手",
    price: 790,
    image: "./images/閃靈快手47.jpeg",
    category: "hot",
  },
  {
    id: "48",
    name: "犯人在跳舞",
    price: 990,
    image: "./images/犯人在跳舞48.webp",
    category: "others",
  },
];
