const products = [
  {
    id: "01",
    name: "妙語說書人",
    price: 550,
    image: "../images/妙語說書人1.jpg",
    category: "funny",
    description: [
      "一款令人感到驚奇、歡樂以及興奮的遊戲",
      "適合讓全家以及朋友們一起享受、出人意料的歡樂派對遊戲",
      "利用你的天賦及直覺，即有機會成為下一個絕佳的妙語說書人！",
    ],
    youtube: "https://www.youtube.com/embed/gfbeG5au_bo?si=jqNVaMedkmCse5bN",
  },
  {
    id: "02",
    name: "矮人礦坑",
    price: 700,
    image: "../images/矮人礦坑2.jpg",
    category: "funny",
    description: [
      "一款簡單且令人捧腹大笑的遊戲",
      "適合各年齡層的玩家",
      "集體策略與運氣的完美結合",
    ],
    youtube: "https://www.youtube.com/embed/fUhEP0XyM00?si=Sm4cadt_vuh63XgT",
  },
  {
    id: "03",
    name: "Bang",
    price: 490,
    description: [
      "一款經典的西部主題卡牌遊戲",
      "玩家分為不同角色，需利用策略和運氣來完成各自的目標",
      "充滿緊張刺激的對抗與合作",
    ],
    image: "../images/bang3.jpeg",
    category: "others",
    youtube: "https://www.youtube.com/embed/eXel1DlunkM?si=A15P8ezYQMp6fWCw",
  },
  {
    id: "04",
    name: "目擊者之夜",
    price: 1100,
    description: [
      "一款扣人心弦的推理遊戲",
      "玩家需要根據線索找出兇手",
      "適合喜愛推理和腦力激盪的玩家",
    ],
    image: "../images/目擊者之夜4.jpeg",
    category: "party",
    youtube: "https://www.youtube.com/embed/Yky_rjYf6ps?si=ZmN_Fwtv46Z5jbNW",
  },
  {
    id: "05",
    name: "卡坦島",
    price: 640,
    description: [
      "一款經典的策略桌遊",
      "玩家需要收集資源，建設道路和城市",
      "需要玩家之間的貿易和合作",
    ],
    image: "../images/卡坦島5.jpeg",
    category: "funny",
    youtube: "https://www.youtube.com/embed/lulnH44AZq8?si=tvsmRUNocEGG9lRt",
  },
  {
    id: "06",
    name: "石器時代",
    price: 690,
    description: [
      "一款模擬石器時代生活的策略遊戲",
      "玩家需要管理資源，發展部落",
      "充滿策略性和趣味性的遊戲體驗",
    ],
    image: "../images/石器時代6.jpeg",
    category: "party",
    youtube: "https://www.youtube.com/embed/Ww-9Dl71jW0?si=ZccnCoSZM3RywsLf",
  },
  {
    id: "07",
    name: "阿瓦隆",
    price: 990,
    description: [
      "一款需要玩家之間互相猜忌的社交遊戲",
      "遊戲中充滿了陰謀和背叛",
      "適合喜愛心理博弈的玩家",
    ],
    image: "../images/阿瓦隆7.png",
    category: "funny",
    youtube: "https://www.youtube.com/embed/Aeu3vMXDuhQ?si=L3_TIGbiv1DZrZ5T",
  },
  {
    id: "08",
    name: "情書",
    price: 1080,
    description: [
      "一款簡單而富有策略性的卡牌遊戲",
      "玩家需要通過猜測對手的手牌來獲勝",
      "快速且富有趣味的遊戲體驗",
    ],
    image: "../images/情書8.jpeg",
    category: "hot",
    youtube: "https://www.youtube.com/embed/It6Kt1T0dD4?si=P7IHusjIKGq6LPCR",
  },
  {
    id: "09",
    name: "拉密",
    price: 780,
    description: [
      "一款需要玩家進行數字排列的策略遊戲",
      "結合了麻將和紙牌的遊戲特色",
      "適合喜愛數字和策略的玩家",
    ],
    image: "../images/拉密9.webp",
    category: "party",
    youtube: "https://www.youtube.com/embed/qIo7k0OQFLY?si=nV-iaE5D0ETdunrU",
  },
  {
    id: "10",
    name: "狼人殺",
    price: 880,
    description: [
      "一款經典的角色扮演推理遊戲",
      "玩家需要通過討論和推理找出狼人",
      "適合多人參與的派對遊戲",
    ],
    image: "../images/狼人殺10.webp",
    category: "hot",
    youtube: "https://www.youtube.com/embed/O3nxEZabceA?si=YTrKi37LzokTQBsD",
  },
  {
    id: "11",
    name: "卡卡頌",
    price: 590,
    description: [
      "一款以城市建設為主題的策略遊戲",
      "玩家需要建設道路、城堡和農田",
      "充滿創意和策略性的遊戲體驗",
    ],
    image: "../images/卡卡頌11.jpeg",
    category: "others",
    youtube: "https://www.youtube.com/embed/HgYPJSpgAFU?si=NpKBpneSxDUhfGnH",
  },
  {
    id: "12",
    name: "德國心臟病",
    price: 490,
    description: [
      "一款反應速度和觀察力的桌遊",
      "玩家需要快速找出相同的圖案",
      "適合各年齡層的快速派對遊戲",
    ],
    image: "../images/德國心臟病12.webp",
    category: "party",
    youtube: "https://www.youtube.com/embed/e3Rl8Aawrdk?si=gjXUxzXcdqorriBd",
  },
  {
    id: "13",
    name: "德國蟑螂",
    price: 650,
    description: [
      "一款簡單且有趣的卡牌遊戲",
      "玩家需要通過策略和運氣避免手中持有蟑螂卡",
      "適合快速上手且有趣的派對遊戲",
    ],
    image: "../images/德國蟑螂13.jpeg",
    category: "others",
    youtube: "https://www.youtube.com/embed/yksUvY0Dnj8?si=ldY0QqUgrElEExul",
  },
  {
    id: "14",
    name: "誰是牛頭王",
    price: 990,
    description: [
      "一款需要玩家進行數字排列的策略遊戲",
      "玩家需要避免收集到牛頭牌",
      "簡單且充滿趣味性的派對遊戲",
    ],
    image: "../images/誰是牛頭王14.jpeg",
    category: "party",
    youtube: "https://www.youtube.com/embed/y7Vt3R3v4pU?si=e5Y7AS_Hhj3ZEBMl",
  },
  {
    id: "15",
    name: "乾杯",
    price: 660,
    description: [
      "一款適合派對場合的飲酒遊戲",
      "玩家需要根據卡牌指示進行飲酒",
      "充滿笑聲和互動的遊戲體驗",
    ],
    image: "../images/乾杯15.jpeg",
    category: "hot",
    youtube: "https://www.youtube.com/embed/lIukdCCLx00?si=agU8-b-W7kqa1mJs",
  },
  {
    id: "16",
    name: "不在場證明",
    price: 780,
    description: [
      "一款推理和策略並重的桌遊",
      "玩家需要根據線索找出兇手",
      "充滿挑戰性的腦力遊戲",
    ],
    image: "../images/不在場證明16.jpeg",
    category: "party",
    youtube: "https://www.youtube.com/embed/hY5PZ3J8qBI?si=-0VET973xLr2BdP6",
  },
  {
    id: "17",
    name: "伊斯坦堡",
    price: 990,
    description: [
      "一款以商業為主題的策略遊戲",
      "玩家需要在伊斯坦堡的市場中進行貿易",
      "充滿策略性和計劃性的遊戲體驗",
    ],
    image: "../images/伊斯坦堡17.jpeg",
    category: "hot",
    youtube: "https://www.youtube.com/embed/DHWpUUtCQWg?si=GcIu3gg_FErdLkLy",
  },
  {
    id: "18",
    name: "作弊飛蛾",
    price: 990,
    description: [
      "一款需要玩家互相猜忌的桌遊",
      "玩家需要通過作弊來獲勝",
      "充滿笑聲和策略性的遊戲體驗",
    ],
    image: "../images/作弊飛蛾18.jpeg",
    category: "hot",
    youtube: "https://www.youtube.com/embed/AFEvKjDp01Y?si=qoIvrE9VEd_7vqv1",
  },
  {
    id: "19",
    name: "你刺我殺他",
    price: 550,
    description: [
      "一款快速上手的卡牌遊戲",
      "玩家需要通過策略和運氣來擊敗對手",
      "適合快速且有趣的派對遊戲",
    ],
    image: "../images/你刺我殺他19.jpeg",
    category: "party",
    youtube: "https://www.youtube.com/embed/NlVx2eoZ2Gk?si=yQqBg0GtQHg-bpFu",
  },
  {
    id: "20",
    name: "冰山疊企鵝",
    price: 880,
    description: [
      "一款需要玩家保持平衡的桌遊",
      "玩家需要將企鵝疊在冰山上",
      "充滿挑戰和趣味性的遊戲體驗",
    ],
    image: "../images/冰山疊企鵝20.jpeg",
    category: "funny",
    youtube: "https://www.youtube.com/embed/OwIfsYzHGCo?si=-LKjNvhjiFQTWapO",
  },
  {
    id: "21",
    name: "估估劃劃",
    price: 650,
    description: [
      "一款趣味十足的畫畫猜題遊戲",
      "玩家需要根據提示畫出圖案讓隊友猜",
      "適合派對和家庭聚會的輕鬆遊戲",
    ],
    image: "../images/估姑劃劃21.webp",
    category: "others",
    youtube: "https://www.youtube.com/embed/MvILBGkK9T8?si=hijNbqDY3dLtQQir",
  },
  {
    id: "22",
    name: "uno",
    price: 750,
    description: [
      "經典的卡牌遊戲，適合各年齡層",
      "規則簡單易懂，但充滿策略性",
      "非常適合派對和家庭娛樂",
    ],
    image: "../images/uno22.webp",
    category: "party",
    youtube: "https://www.youtube.com/embed/JHBrLEGn8bU?si=ODjfBpvqdqudk7AS",
  },
  {
    id: "23",
    name: "動手不動口",
    price: 790,
    description: [
      "需要玩家利用肢體語言進行交流的遊戲",
      "適合派對和家庭聚會",
      "充滿笑聲和互動性",
    ],
    image: "../images/動手不動口23.webp",
    category: "party",
    youtube: "https://www.youtube.com/embed/3jEqYAFp_FI?si=iYDnF7mzlMCeAmNL",
  },
  {
    id: "24",
    name: "快手疊杯",
    price: 740,
    description: [
      "需要快速反應和手眼協調的遊戲",
      "玩家需要按照指示快速堆疊杯子",
      "適合各年齡層的趣味挑戰",
    ],
    image: "../images/快手疊杯24.webp",
    category: "funny",
    youtube: "https://www.youtube.com/embed/_GF6tDYrrv0?si=p3pWX39JB_fjb_nA",
  },
  {
    id: "25",
    name: "奶酪大盜",
    price: 550,
    description: [
      "一款需要玩家合作和策略的桌遊",
      "玩家需要一起偷取奶酪並避免被抓",
      "充滿緊張和樂趣的遊戲體驗",
    ],
    image: "../images/奶酪大盜25.webp",
    category: "hot",
    youtube: "https://www.youtube.com/embed/Panhho_98iY?si=2IAtZ7vEMfvQ1U-H",
  },
  {
    id: "26",
    name: "傳情畫意",
    price: 750,
    description: [
      "玩家需要根據卡牌提示畫出圖案讓隊友猜",
      "充滿創意和笑聲的遊戲",
      "適合派對和家庭聚會",
    ],
    image: "../images/傳情畫意26.webp",
    category: "others",
    youtube: "https://www.youtube.com/embed/zQI9glI2-J0?si=6APNUQHE_vxlAyo8",
  },
  {
    id: "27",
    name: "腦洞量表",
    price: 560,
    description: [
      "測試玩家創造力和想像力的遊戲",
      "適合喜歡挑戰思維極限的玩家",
      "充滿驚喜和趣味的體驗",
    ],
    image: "../images/腦洞量表27.webp",
    category: "hot",
    youtube: "https://www.youtube.com/embed/FVFWJCEEUZE?si=b10eGwKBtCxJ3NCX",
  },
  {
    id: "28",
    name: "馬可波羅",
    price: 850,
    description: [
      "一款以貿易和探險為主題的策略遊戲",
      "玩家需要進行貿易和探索來獲取資源",
      "充滿策略和計劃性的遊戲體驗",
    ],
    image: "../images/馬可波羅28.webp",
    category: "funny",
    youtube: "https://www.youtube.com/embed/s2BJR7RHKYQ?si=uYwPMNiFGO4RPTea",
  },
  {
    id: "29",
    name: "名畫神偷",
    price: 750,
    description: [
      "玩家需要扮演神偷，盜取名畫",
      "充滿緊張和刺激的遊戲",
      "適合喜歡挑戰和策略的玩家",
    ],
    image: "../images/名畫神偷29.jpeg",
    category: "party",
    youtube: "https://www.youtube.com/embed/L-wW93R_nmc?si=DNJXncjXDEDySiy8",
  },
  {
    id: "30",
    name: "城市規劃師",
    price: 540,
    description: [
      "玩家需要設計和建設自己的城市",
      "充滿策略性和創造力的遊戲",
      "適合喜愛建設和規劃的玩家",
    ],
    image: "../images/城市規劃師30.jpeg",
    category: "others",
    youtube: "https://www.youtube.com/embed/EgNHMgOJY_0?si=C4jI-GlOcvAYenC_",
  },
  {
    id: "31",
    name: "萬獸酒吧",
    price: 770,
    description: [
      "一款以動物為主題的經營類遊戲",
      "玩家需要經營自己的酒吧並吸引顧客",
      "充滿趣味和挑戰的遊戲體驗",
    ],
    image: "../images/萬獸酒吧31.jpeg",
    category: "others",
    youtube: "https://www.youtube.com/embed/QGVZA5osuJM?si=0od2oJctAbBkF0_i",
  },
  {
    id: "32",
    name: "不要命的冒險",
    price: 880,
    description: [
      "玩家需要在遊戲中完成各種驚險的任務",
      "充滿挑戰和刺激的遊戲",
      "適合喜愛冒險和挑戰的玩家",
    ],
    image: "../images/不要命的冒險32.jpeg",
    category: "hot",
    youtube: "https://www.youtube.com/embed/hKFLIt2CxIc?si=LNt9KFGJX1H-V5lZ",
  },
  {
    id: "33",
    name: "呼拉大師",
    price: 940,
    description: [
      "一款以呼拉圈為主題的趣味遊戲",
      "玩家需要完成各種呼拉圈挑戰",
      "充滿笑聲和互動性的遊戲",
    ],
    image: "../images/呼拉大師33.jpeg",
    category: "funny",
    youtube: "https://www.youtube.com/embed/H4yKOW4Xm8Y?si=vNlTGBPnAE9WR16x",
  },
  {
    id: "34",
    name: "惡魔島",
    price: 690,
    description: [
      "一款以惡魔島為背景的冒險遊戲",
      "玩家需要在島上進行探索和生存",
      "充滿挑戰和策略性的遊戲體驗",
    ],
    image: "../images/惡魔島34.jpeg",
    category: "others",
    youtube: "https://www.youtube.com/embed/uGingy3hL3I?si=_45El5TIjyFhgg66",
  },
  {
    id: "35",
    name: "滿腦子番茄",
    price: 550,
    description: [
      "一款需要快速反應的趣味遊戲",
      "玩家需要避免被番茄擊中",
      "充滿笑聲和刺激的遊戲",
    ],
    image: "../images/滿腦子番茄35.webp",
    category: "party",
    youtube: "https://www.youtube.com/embed/RnY9jXV5_u0?si=xMgeIRzgL6wG5L4R",
  },
  {
    id: "36",
    name: "瘋狂科學家",
    price: 790,
    description: [
      "一款以科學實驗為主題的趣味遊戲",
      "玩家需要進行各種瘋狂的實驗",
      "充滿創意和挑戰性的遊戲",
    ],
    image: "../images/瘋狂科學家36.webp",
    category: "funny",
    youtube: "https://www.youtube.com/embed/ETAMco9FUIg?si=WPpvRmmAS2IFXMHk",
  },
  {
    id: "37",
    name: "起司天堂",
    price: 1200,
    description: [
      "一款以起司為主題的經營遊戲",
      "玩家需要經營自己的起司店",
      "充滿策略和趣味的遊戲體驗",
    ],
    image: "../images/起司天堂37.webp",
    category: "hot",
    youtube: "https://www.youtube.com/embed/aAzwpCeA-0M?si=9cq7xrF3T307y4XK",
  },
  {
    id: "38",
    name: "抓鬼大隊",
    price: 640,
    description: [
      "玩家需要組成隊伍來抓鬼",
      "充滿緊張和刺激的遊戲",
      "適合喜愛冒險和驚悚的玩家",
    ],
    image: "../images/抓鬼大隊38.webp",
    category: "hot",
    youtube: "https://www.youtube.com/embed/a8jkXqn25HA?si=KsgI2hcVbFfgcLcx",
  },
  {
    id: "39",
    name: "動物疊疊樂",
    price: 550,
    description: [
      "一款需要玩家保持平衡的桌遊",
      "玩家需要將動物疊在一起",
      "充滿挑戰和趣味性的遊戲體驗",
    ],
    image: "../images/動物疊疊樂39.webp",
    category: "party",
    youtube: "https://www.youtube.com/embed/Kg0hTQlpOew?si=exNkSQEkhzZGWvjn",
  },
  {
    id: "40",
    name: "種豆",
    price: 1300,
    description: [
      "一款以種豆為主題的策略遊戲",
      "玩家需要種植和收穫不同的豆子",
      "充滿策略性和計劃性的遊戲",
    ],
    image: "../images/種豆40.webp",
    category: "funny",
    youtube: "https://www.youtube.com/embed/z74pTIuW1dQ?si=ep5dHlcUHrIbgf-1",
  },
  {
    id: "41",
    name: "陛下",
    price: 870,
    description: [
      "一款以王室爭權為背景的策略遊戲",
      "玩家需要競爭成為最強大的國王",
      "充滿政治陰謀和權力爭奪的遊戲體驗",
    ],
    image: "../images/陛下41.webp",
    category: "others",
    youtube: "https://www.youtube.com/embed/LAyKmUdqmEo?si=okj5d-e39hZRLCrS",
  },
  {
    id: "42",
    name: "上流社會",
    price: 660,
    description: [
      "一款以社會名流為背景的生活遊戲",
      "玩家需要在上流社會爭取地位和財富",
      "充滿精英生活和社交競爭的遊戲",
    ],
    image: "../images/上流社會42.webp",
    category: "others",
    youtube: "https://www.youtube.com/embed/MWSSPMl3ECY?si=a4EeSsibenO6m1Ye",
  },
  {
    id: "43",
    name: "病毒在跳舞",
    price: 770,
    description: [
      "一款以病毒和免疫系統為主題的遊戲",
      "玩家需要控制病毒來感染宿主",
      "充滿科學和娛樂性的遊戲體驗",
    ],
    image: "../images/病毒在跳舞43.webp",
    category: "hot",
    youtube: "https://www.youtube.com/embed/2Hf3F_PEc1c?si=ubHnxhGpet0jzvaa",
  },
  {
    id: "44",
    name: "瘟疫危機",
    price: 1080,
    description: [
      "一款以瘟疫爆發為主題的求生遊戲",
      "玩家需要阻止瘟疫的傳播並找到解藥",
      "充滿緊張和刺激的遊戲體驗",
    ],
    image: "../images/瘟疫危機44.webp",
    category: "others",
    youtube: "https://www.youtube.com/embed/g5AfK-QwDaY?si=09x-yxNdt2Fre48L",
  },
  {
    id: "45",
    name: "黃牌",
    price: 580,
    description: [
      "一款足球比賽管理遊戲",
      "玩家需要管理自己的球隊並贏得比賽",
      "充滿足球激情和策略性的遊戲",
    ],
    image: "../images/黃牌45.jpeg",
    category: "funny",
    youtube: "https://www.youtube.com/embed/236Ob3rKhzg?si=rdiwbgkY8zlH3twT",
  },
  {
    id: "46",
    name: "動物園",
    price: 480,
    description: [
      "一款以動物園經營為主題的遊戲",
      "玩家需要建設和管理自己的動物園",
      "充滿創意和趣味性的遊戲體驗",
    ],
    image: "../images/動物園46.jpeg",
    category: "funny",
    youtube: "https://www.youtube.com/embed/rX6UAcNQmiY?si=Wy-k8rOtqimMaO_w",
  },
  {
    id: "47",
    name: "閃靈快手",
    price: 790,
    description: [
      "一款以超級英雄為主題的快節奏遊戲",
      "玩家需要利用超能力擊敗敵人",
      "充滿動作和刺激的遊戲體驗",
    ],
    image: "../images/閃靈快手47.jpeg",
    category: "hot",
    youtube: "https://www.youtube.com/embed/VFBFeYn6UAo?si=3HVPIpBVsN0R05_f",
  },
  {
    id: "48",
    name: "犯人在跳舞",
    price: 990,
    description: [
      "一款以監獄生活為背景的音樂遊戲",
      "玩家需要學習舞蹈並參加比賽",
      "充滿音樂和舞蹈樂趣的遊戲",
    ],
    image: "../images/犯人在跳舞48.webp",
    category: "others",
    youtube: "https://www.youtube.com/embed/47Nd0jGZ98M?si=o2lo1-OQQQI7lTkl",
  },
];
